version: "3.9"
services:
  mysql:
    image: mariadb:10.11
    container_name: mycellius-mysql
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: mycellius
      MARIADB_USER: mycellius
      MARIADB_PASSWORD: mycellius
    volumes:
      - mycellius_db:/var/lib/mysql

  api:
    build: ../../api
    container_name: mycellius-api
    restart: unless-stopped
    environment:
      MYCELLIUS_CORS_ALLOWED_ORIGINS: "http://100.66.190.108,http://192.168.1.53"
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mycellius?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: mycellius
      SPRING_DATASOURCE_PASSWORD: mycellius
      MYCELLIUS_ENV: ${MYCELLIUS_ENV}
      MYCELLIUS_VERSION: ${MYCELLIUS_VERSION}
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mycellius_db: